### ISSUE TITLE
请教doQCRLSC

### ISSUE THREAD

**Issue by asepsisWu** [wenbostar/metaX#13]
样本校正相关的下面3行代码
[ mpa <- peaksData %>% dplyr::group_by(ID) %>% dplyr::summarise(mpa=median(value,na.rm = TRUE))](https://github.com/wenbostar/metaX/blob/2f046533310b0de27e3ea1e1a2686ea9219a8951/R/metaX.R#L823)
   [ peaksData <- dplyr::mutate(peaksData,valuePredict=valuePredict/mpa)](https://github.com/wenbostar/metaX/blob/2f046533310b0de27e3ea1e1a2686ea9219a8951/R/metaX.R#L828)
   [ peaksData$valueNorm <- peaksData$value/peaksData$valuePredict](https://github.com/wenbostar/metaX/blob/2f046533310b0de27e3ea1e1a2686ea9219a8951/R/metaX.R#L831)
我理解mpa是raw.value的中位值，valuePredict/mpa的比值是校正系数。valueNorm应该是raw.value * 校正系数，而不是除以校正系数，与第三行代码的思想不一致。
按照第三行代码计算得到的QC.valueNorm与 QC.valuePredict的值是不一样的。
请指正。

**Comment by wenbostar** [comment]
**valuePredict** is a vector of normalization factors from SVR. They are the predicted intensities which are used to normalize raw intensities from non-QC samples. After normalization, QC samples should have similar normalized intensities if the data is well normalized. It's right that QC.valueNorm is different from QC.valuePredict since QC.valuePredict is normalization factor: valueNorm = (raw_intensity / valuePredict) * mpa.
